### ISSUE TITLE
Release new version.

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/read-activity#33]
The current version on aslo is v119, while v120 comes with sucrose. So it is necessary to release the latest version.
@nswarup14 you might be interested. Thanks!

**Comment by quozl** [comment]
Use great care?  Any release to activities.sugarlabs.org needs testing on Fedora 18 first, otherwise there are hundreds of thousands of children who would not be impressed with our quality control.  I've been using the _v118_ branch instead, and should really downgrade activities.sugarlabs.org from v119 to v118.1. 

v122 was the latest release.  It ports to WebKit2, which is not working very well on Fedora 18.

v120 is in Ubuntu 18.04, 18.10, and Debian Buster.

v121 is in Ubuntu 19.04, 19.10 and Debian Sid.

v122 is in Fedora.

The _master_ branch is used for up to date Fedora, Debian, and Ubuntu.

**Comment by nswarup14** [comment]
@quozl 
Since v120 is stable on Ubuntu 18.04, 18.10 and Debian Buster, and if, after testing extensively on Fedora 18, the activity is shown to function well and is stable, it is eligible for release right?
Thanks.

**Comment by quozl** [comment]
@nswarup14, worth a try to find out if it functions well.  You'll need a Fedora 18 VM.  Meanwhile v122 is released here on GitHub and the changes since are minimal.

**Comment by quozl** [comment]
p.s. to me _stable_ means "no plans to change", but I take it you were using it to mean "functions well".

**Comment by nswarup14** [comment]
Thanks @quozl 
I shall try to get a running Fedora 18 VM in the couple of days to test both v120 and v122.

**Comment by quozl** [comment]
v123 released.
